#!/bin/bash
source "$CPU_PYTHON_V_ENV"

# Leggi il primo parametro
case "$1" in
    -coe)
        # Esegui lo script Python per "coe"
        echo "Eseguo lo script Python per 'coe'..."
        python3 "${CPU_PYTHON_DIR}/elfToCoe.py" "${@:2}";
        ;;
    -sv)
        # Esegui lo script Python per "verilog"
        echo "Eseguo lo script Python per 'verilog'..."
        python3 "${CPU_PYTHON_DIR}/elfToVerilog.py" "${@:2}";
        ;;
    -c)
        # Esegui lo script Python per "c"
        echo "Eseguo lo script Python per 'c'..."
        python3 "${CPU_PYTHON_DIR}/elfToC.py" "${@:2}";
        ;;
    -s)
        # Controlla se il secondo parametro è un file esistente, in caso positivo esegui quello script
        if [ -f "$2" ]; then
            echo "Eseguo lo script Python per 'script'..."
            python3 "$2" "${@:3}";
        else
            echo "Errore: il file '$2' non esiste."
        fi
        ;;
    *)
        # Gestione dei valori non validi
        echo "Errore: primo parametro non valido. Usa uno tra: -coe, -sv, -c"
        # exit 1
        ;;
esac
deactivate;